// <copyright file="GlobalSuppressions.cs" company="Ashi Chamarasinghe">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1400:Access modifier should be declared", Justification = "<This methods are written by form therefore doesn't need to change its access specifier>", Scope = "type", Target = "~T:Homework3.Program")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<This methods are written by form when a button is clicked.Therefore, can not change names>", Scope = "member", Target = "~M:Homework3.Form1.loadFromFileToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<This methods are written by form when a button is clicked.Therefore, can not change names>", Scope = "member", Target = "~M:Homework3.Form1.loadFibonacciNumbersfirst50ToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "<This methods are written by form when a button is clicked.Therefore, can not change names>", Scope = "member", Target = "~M:Homework3.Form1.loadFibonacciNumbersfirst50ToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "<This methods are written by form when a button is clicked.Therefore, can not change names>", Scope = "member", Target = "~M:Homework3.Form1.loadFibonacciNumbersfirst100ToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<This methods are written by form when a button is clicked.Therefore, can not change names>", Scope = "member", Target = "~M:Homework3.Form1.loadFibonacciNumbersfirst100ToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "<This methods are written by form when a button is clicked.Therefore, can not change names>", Scope = "member", Target = "~M:Homework3.Form1.saveToFileToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<This methods are written by form when a button is clicked.Therefore, can not change names>", Scope = "member", Target = "~M:Homework3.Form1.saveToFileToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "<This methods are written by form when a button is clicked.Therefore, can not change names>", Scope = "member", Target = "~M:Homework3.Form1.exitToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<This methods are written by form when a button is clicked.Therefore, can not change names>", Scope = "member", Target = "~M:Homework3.Form1.exitToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "<This methods are written by form when a button is clicked.Therefore, can not change names>", Scope = "member", Target = "~M:Homework3.Form1.viewHelpToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<This methods are written by form when a button is clicked.Therefore, can not change names>", Scope = "member", Target = "~M:Homework3.Form1.viewHelpToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "This methods are written by form when a button is clicked.Therefore, can not change names > ", Scope = "member", Target = "~M:Homework3.Form1.aboutToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<This methods are written by form when a button is clicked.Therefore, can not change names>", Scope = "member", Target = "~M:Homework3.Form1.aboutToolStripMenuItem_Click(System.Object,System.EventArgs)")]
